### PR TITLE
Only merge coverage for covered files when using Single Cov

### PR DESCRIPTION
**Pull request by mervync**
When using `single_cov`, only merge coverage for covered files. Merging coverage for all files is unnecessary and can impact performance significantly on large projects or projects that use many gems.

### CODE REVIEW

**Review by grosser — COMMENTED** [review]
a few issues:
- don't think this works, forking-test-runner won't load all gems ?
- it says `if defined?(SimpleCov)`
- it looks kinda copy-pasty
- it does not have tests

**Comment by mervync** [comment]
> it says if defined?(SimpleCov)

oops! fixed.

> don't think this works, forking-test-runner won't load all gems ?

not sure what you mean.

**Comment by grosser** [comment]
does the forking-test-runner cli even load the single-cov gem ? <-> can it detect this ?

**Comment by mervync** [comment]
single_cov should be loaded by the time `merge_coverage` is called (presumably by the application?)

**Pull request closed without merging**
