### PR TITLE
Propagate RSpec exit code from the child process

### PR DESCRIPTION
**Pull request by brrygrdn**
Thanks for your work on this gem! I've been using it to mitigate some memory issues in a large RSpec/Capybara test suite on Travis CI with success, but I did notice that the overall `forking-test-runner` command was finishing with an exit code of 0 despite some failures - this patch got me working.

### CODE REVIEW

**Comment by grosser** [comment]
wow ... that's some nasty bug ...
I tried to use it for rspec, but it got way to slow compared to just running everything in parallel_tests ... so never really used that codepath :D

**Comment by grosser** [comment]
thx for the patch, 0.6.0 is out!

**Comment by grosser** [comment]
also great to see some tests being added ;)

**Comment by brrygrdn** [comment]
Nice, thanks!

**Pull request merged**
